[package]
name = "catanatron_rust"
version = "0.1.0"
edition = "2021"

[lib]
name = "catanatron_rust"
path = "src/lib.rs"

[dependencies]
rand = "0.8"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "copy_benchmark"
harness = false
