services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=catanatron
      - POSTGRES_PASSWORD=victorypoint
      - POSTGRES_DB=catanatron_db
    ports:
      - 5432:5432
    volumes:
      - ./db-data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -d postgresql://catanatron:victorypoint@db:5432/catanatron_db",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
  server:
    build:
      context: .
      dockerfile: Dockerfile.web
    environment:
      - DATABASE_URL=postgresql://catanatron:victorypoint@db:5432/catanatron_db
      - PYTHONUNBUFFERED=1
    ports:
      - 5001:5001
    stdin_open: true
    restart: always
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
  websocketllm:
    build:
      context: .
      dockerfile: Dockerfile.uv
    environment:
      - PYTHONUNBUFFERED=1
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    ports:
      - 8001:8001
      - 8002:8002
      - 8003:8003
      - 8004:8004
      - 8100:8100 # HTTP Status API
    stdin_open: true
    restart: always
    volumes:
      - .:/app
    depends_on:
      - server
  react-ui:
    build: ./ui
    # environment:
    #   - CTRON_API_URL=http://${HOST}:5001
    #   - CTRON_WEBSOCKET_ENGINE_URL=http://${HOST}:8100
    #   - CTRON_LLM_API_BASE_URL=http://${LLM_HOST}:8000
    ports:
      - 3000:80
    stdin_open: true
    volumes:
      - /app/node_modules
      - ./ui:/app
